version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prescriptiondb
    container_name: postgres-back
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - applicant_registration

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prescription_back
    environment:
      - PORT=${PORT}
    ports:
      - '4242:4242'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - applicant_registration

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - applicant_registration

networks:
  applicant_registration:
    external: true

volumes:
  pgdata:
